use std::fs;

use bixbite::{commands::build, emitter::ruby::RubyEmitter, project::Project};
use tempfile::tempdir;

#[test]
fn build_project_writes_expected_ruby_output() {
    let temp = tempdir().expect("temp dir should be created");
    let source_dir = temp.path().join("src");
    fs::create_dir_all(&source_dir).expect("source dir should be created");
    fs::write(
        source_dir.join("example.bixb"),
        concat!(
            "def greet(name: String, loud: Boolean = false) -> String\n",
            "  name\n",
            "end\n"
        ),
    )
    .expect("source file should be written");

    let project = Project::load(temp.path()).expect("project should load");
    let report = build::build_project(&project, &RubyEmitter).expect("build should succeed");

    assert!(report.diagnostics.is_empty());
    assert_eq!(report.summary.discovered_files, 1);
    assert_eq!(report.summary.written_files, 1);
    assert_eq!(
        fs::read_to_string(temp.path().join("build/example.rb")).expect("output should exist"),
        concat!(
            "# GENERATED BY BIXBITE - DO NOT EDIT\n",
            "# Source: src/example.bixb\n",
            "\n",
            "def greet(name, loud = false)\n",
            "  name\n",
            "end\n"
        )
    );
}

#[test]
fn build_project_skips_unchanged_outputs() {
    let temp = tempdir().expect("temp dir should be created");
    let source_dir = temp.path().join("src");
    fs::create_dir_all(&source_dir).expect("source dir should be created");
    fs::write(
        source_dir.join("example.bixb"),
        concat!(
            "def add(x: Integer, y: Integer) -> Integer\n",
            "  x + y\n",
            "end\n"
        ),
    )
    .expect("source file should be written");

    let project = Project::load(temp.path()).expect("project should load");

    let first = build::build_project(&project, &RubyEmitter).expect("first build should succeed");
    let second = build::build_project(&project, &RubyEmitter).expect("second build should succeed");

    assert_eq!(first.summary.written_files, 1);
    assert_eq!(second.summary.discovered_files, 1);
    assert_eq!(second.summary.written_files, 0);
}

#[test]
fn build_project_reports_relative_diagnostic_paths_and_does_not_write_invalid_output() {
    let temp = tempdir().expect("temp dir should be created");
    let source_dir = temp.path().join("src");
    fs::create_dir_all(&source_dir).expect("source dir should be created");
    fs::write(
        source_dir.join("bad.bixb"),
        "def f(x: Integer, y) -> Integer\n",
    )
    .expect("source file should be written");

    let project = Project::load(temp.path()).expect("project should load");
    let report = build::build_project(&project, &RubyEmitter).expect("build should complete");

    assert!(report.diagnostics.has_errors());
    assert_eq!(report.summary.discovered_files, 1);
    assert_eq!(report.summary.written_files, 0);
    assert_eq!(report.diagnostics.diagnostics[0].file, "src/bad.bixb");
    assert!(!temp.path().join("build/bad.rb").exists());
}
