use std::path::Path;

use bixbite::{
    emitter::{ruby::RubyEmitter, Emitter},
    lexer, parser,
};

fn emit(source: &str, path: &str) -> String {
    let unit = parser::parse(lexer::tokenize(source, path));
    assert!(
        !unit.diagnostics.has_errors(),
        "expected emitter fixture to parse cleanly"
    );
    RubyEmitter.emit(&unit, Path::new(path))
}

#[test]
fn ruby_emitter_adds_header_and_rewrites_typed_def_lines() {
    let output = emit(
        concat!("def add(x: Int, y: Int) -> Int\n", "  x + y\n", "end\n"),
        "src/example.bixb",
    );

    assert_eq!(
        output,
        concat!(
            "# GENERATED BY BIXBITE - DO NOT EDIT\n",
            "# Source: src/example.bixb\n",
            "\n",
            "def add(x, y)\n",
            "  x + y\n",
            "end\n"
        )
    );
}

#[test]
fn ruby_emitter_preserves_defaults_and_special_method_names() {
    let output = emit(
        concat!(
            "def self.encode(id: Int, data: Str = \"00\") -> Str\n",
            "  data\n",
            "end\n",
            "\n",
            "def ok?() -> TrueClass\n",
            "  true\n",
            "end\n",
            "\n",
            "def set_name=(name: Str) -> Str\n",
            "  @name = name\n",
            "end\n"
        ),
        "src/example.bixb",
    );

    assert!(output.contains("def self.encode(id, data = \"00\")\n"));
    assert!(output.contains("def ok?()\n"));
    assert!(output.contains("def set_name=(name)\n"));
    assert!(!output.contains(": Int"));
    assert!(!output.contains("-> Str"));
}

#[test]
fn ruby_emitter_normalizes_whitespace_by_emitting_canonical_def_lines() {
    let output = emit(
        concat!(
            "def   greet(name  :   Str, loud:Bool = false)   ->   Str\n",
            "  puts name\n",
            "end\n"
        ),
        "src/example.bixb",
    );

    assert!(output.contains("def greet(name, loud = false)\n"));
    assert!(output.contains("  puts name\nend\n"));
}
