use std::path::Path;

use bixbite::{
    ast::CompilationUnit,
    emitter::{ruby_sorbet::RubySorbetEmitter, Emitter},
};

#[test]
fn ruby_sorbet_emitter_adds_header_and_source() {
    let unit = CompilationUnit::from_source("puts :ok\n".to_owned());
    let emitter = RubySorbetEmitter;

    let output = emitter.emit(&unit, Path::new("src/example.bixb"));

    assert!(output.starts_with("# GENERATED BY BIXBITE - DO NOT EDIT\n"));
    assert!(output.contains("# Source: src/example.bixb\n\n"));
    assert!(output.ends_with("puts :ok\n"));
}
