use std::path::Path;

use crate::ast::CompilationUnit;

use super::Emitter;

/// Emits Ruby source with the standard Bixbite generated header.
#[derive(Debug, Clone, Copy, Default)]
pub struct RubyEmitter;

impl Emitter for RubyEmitter {
    fn emit(&self, unit: &CompilationUnit, source_path: &Path) -> String {
        let mut output = String::new();
        let source_header = source_path.to_string_lossy().replace('\\', "/");
        output.push_str("# GENERATED BY BIXBITE - DO NOT EDIT\n");
        output.push_str(&format!("# Source: {}\n\n", source_header));
        output.push_str(&unit.source);
        output
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::{ast::CompilationUnit, diagnostic::DiagnosticReport, emitter::Emitter};

    use super::RubyEmitter;

    #[test]
    fn test_ruby_emitter_normalizes_source_header_separators() {
        let unit = CompilationUnit::from_source(
            "puts 'hi'\n".to_string(),
            Vec::new(),
            DiagnosticReport::default(),
        );
        let output = RubyEmitter.emit(&unit, Path::new("a\\b\\c.bixb"));
        assert!(output.contains("# Source: a/b/c.bixb"));
    }
}
