use std::path::Path;

use crate::ast::CompilationUnit;

use super::Emitter;

/// Emits Ruby source with the standard Bixbite generated header.
#[derive(Debug, Clone, Copy, Default)]
pub struct RubyEmitter;

impl Emitter for RubyEmitter {
    fn emit(&self, unit: &CompilationUnit, source_path: &Path) -> String {
        let mut output = String::new();
        let source_header = source_path.to_string_lossy().replace('\\', "/");
        output.push_str("# GENERATED BY BIXBITE - DO NOT EDIT\n");
        output.push_str(&format!("# Source: {}\n\n", source_header));
        output.push_str(&rewrite_source(unit));
        normalize_newlines(&output)
    }
}

fn rewrite_source(unit: &CompilationUnit) -> String {
    let mut output = String::new();
    let mut last_index = 0;

    for method in &unit.typed_methods {
        let start = method.signature_byte_range.start;
        let end = method.signature_byte_range.end;
        if start < last_index || end > unit.source.len() {
            continue;
        }

        output.push_str(unit.source.get(last_index..start).unwrap_or(""));
        output.push_str(&emit_method_signature(method));
        last_index = end;
    }

    output.push_str(unit.source.get(last_index..).unwrap_or(""));
    output
}

fn emit_method_signature(method: &crate::ast::TypedMethod) -> String {
    let params = method
        .params
        .iter()
        .map(|param| match &param.default {
            Some(default) => format!("{} = {}", param.name, default),
            None => param.name.clone(),
        })
        .collect::<Vec<_>>()
        .join(", ");

    format!("def {}({})", method.name, params)
}

fn normalize_newlines(contents: &str) -> String {
    contents.replace("\r\n", "\n").replace('\r', "\n")
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::{diagnostic::DiagnosticReport, emitter::Emitter, lexer, parser};

    use super::RubyEmitter;

    #[test]
    fn test_ruby_emitter_normalizes_source_header_separators() {
        let unit = crate::ast::CompilationUnit::from_source(
            "puts 'hi'\n".to_string(),
            Vec::new(),
            DiagnosticReport::default(),
        );
        let output = RubyEmitter.emit(&unit, Path::new("a\\b\\c.bixb"));
        assert!(output.contains("# Source: a/b/c.bixb"));
    }

    #[test]
    fn test_ruby_emitter_rewrites_typed_signature() {
        let source = "def add(x: Int, y: Int = 1) -> Int\n  x + y\nend\n";
        let unit = parser::parse(lexer::tokenize(source, "src/add.bixb"));
        let output = RubyEmitter.emit(&unit, Path::new("src/add.bixb"));

        assert!(output.contains("def add(x, y = 1)\n  x + y\nend\n"));
        assert!(!output.contains(": Int"));
        assert!(!output.contains("-> Int"));
    }
}
