use std::path::Path;

use crate::ast::CompilationUnit;

use super::Emitter;

#[derive(Debug, Clone, Copy, Default)]
pub struct RubyEmitter;

impl Emitter for RubyEmitter {
    fn emit(&self, unit: &CompilationUnit, source_path: &Path) -> String {
        let mut output = String::new();
        output.push_str("# GENERATED BY BIXBITE - DO NOT EDIT\n");
        output.push_str(&format!("# Source: {}\n\n", source_path.to_string_lossy()));
        output.push_str(&unit.source);
        output
    }
}
